import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
const source = fs.readFileSync(path.join(here, '..', 'desk-notes-common', 'desk-notes-core.js'), 'utf8');
const sandbox = { console, Math, Date, JSON, String, Number, Object, Array, globalThis: null, document: { readyState: 'loading', addEventListener() {} }, addEventListener() {}, innerWidth: 840, innerHeight: 344 };
sandbox.globalThis = sandbox;
vm.createContext(sandbox);
vm.runInContext(source, sandbox, { filename: 'desk-notes-core.js' });
const api = sandbox.__deskNotesTest;
if (!api) throw new Error('Desk Notes test API missing');
function assert(v, m) { if (!v) throw new Error(m); }
let b = api.parseBoard('TODAY', ['[ ] One','Plain note','[x] Done','! [ ] Pinned'], 0, 8);
assert(b.count === 4, 'four entries parsed');
assert(b.cards[0].items[0].checklist === true, 'unchecked checklist parsed');
assert(b.cards[0].items[1].checklist === false, 'plain note parsed');
assert(b.cards[0].items[2].initiallyDone === true, 'done checklist parsed');
assert(b.cards[0].items[3].pinned === true, 'pin prefix parsed');
b = api.parseBoard('WORK', ['## Launch','# Video','[ ] Final render','','## Admin','Email sponsor'], 1, 16);
assert(b.cards.length === 2, 'blank line creates note card');
assert(b.cards[0].title === 'Launch' && b.cards[0].category === 'Video', 'card metadata parsed');
assert(b.cards[1].title === 'Admin', 'second card title parsed');
const capped = api.parseBoard('CAP', Array.from({length:20}, (_,i)=>'[ ] Item '+i), 0, 8);
assert(capped.count === 8, 'lite limit enforced');
const duplicates = api.parseBoard('DUP', ['[ ] Same','[ ] Same'], 0, 8).cards[0].items;
assert(duplicates[0].id !== duplicates[1].id, 'duplicate lines get stable distinct ids');
assert(Object.keys(api.themes).length >= 6, 'six tasteful themes');
console.log('DESK NOTES VERIFY PASS');
