import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const SLOTS={S_H:[840,344],S_V:[696,416],M_H:[840,696],M_V:[696,840],L_H:[1688,696],L_V:[696,1688],XL_H:[2536,696],XL_V:[696,2536]};

function weatherApiPayload(name='Phoenix',mode='clear'){
  const base=new Date();base.setMinutes(0,0,0);const condition=mode==='rain'?{text:'Moderate rain',code:1189}:mode==='snow'?{text:'Moderate snow',code:1219}:{text:'Clear',code:1000};const days=[];
  for(let d=0;d<3;d++){const date=new Date(base);date.setDate(date.getDate()+d);const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),da=String(date.getDate()).padStart(2,'0'),dateText=`${y}-${m}-${da}`,hours=[];
    for(let h=0;h<24;h++){const epoch=Math.floor(new Date(y,date.getMonth(),date.getDate(),h).getTime()/1000),isDay=h>=6&&h<19,temp=mode==='hot'?115+(h%3):mode==='cold'?-18+(h%4):72+Math.round(Math.sin(h/4)*7);hours.push({time_epoch:epoch,temp_f:temp,temp_c:(temp-32)*5/9,feelslike_f:temp+(mode==='hot'?7:-2),feelslike_c:((temp+(mode==='hot'?7:-2))-32)*5/9,chance_of_rain:mode==='rain'?82:5,chance_of_snow:mode==='snow'?78:0,precip_in:mode==='rain'?.12:mode==='snow'?.03:0,precip_mm:mode==='rain'?3:mode==='snow'?.8:0,wind_mph:10+(h%4),wind_kph:(10+(h%4))*1.609,wind_degree:(210+h*8)%360,uv:isDay?5:0,is_day:isDay?1:0,condition});}
    days.push({date:dateText,day:{maxtemp_f:mode==='hot'?121:mode==='cold'?-6:86,mintemp_f:mode==='hot'?94:mode==='cold'?-26:66,maxtemp_c:mode==='hot'?49.4:mode==='cold'?-21.1:30,mintemp_c:mode==='hot'?34.4:mode==='cold'?-32.2:18.9,condition},astro:{sunrise:'6:12 AM',sunset:'6:48 PM'},hour:hours});}
  const current=days[0].hour[new Date().getHours()];return {location:{name,region:'Arizona',country:'United States',lat:33.4484,lon:-112.074,tz_id:'America/Phoenix'},current:{temp_f:current.temp_f,temp_c:current.temp_c,feelslike_f:current.feelslike_f,feelslike_c:current.feelslike_c,wind_mph:current.wind_mph,wind_kph:current.wind_kph,wind_degree:current.wind_degree,is_day:current.is_day,condition},forecast:{forecastday:days}};
}
async function baseInit(page,{pro=false,fixture='clear',unit='°F',preview=false,stale=false,locations=[]}={}){await page.addInitScript(({fixture,unit,preview,stale,locations})=>{window.iCUE={defaultTemperatureUnit:()=>unit,isPreview:preview,iCUELanguage:'en'};window.uniqueId='qa-instance';window.__weatherTimelineFixture=fixture;window.__weatherTimelineStale=stale;window.temperatureUnits='auto';window.theme='sky';window.refreshMinutes=20;window.weatherApiKey='';window.location1=locations[0]||'Phoenix';window.location2=locations[1]||'';window.location3=locations[2]||'';},{fixture,unit,preview,stale,locations});}
async function waitReady(page){await page.waitForSelector('#weatherStage[data-ready="true"]',{timeout:8000});}
async function assertGeometry(page,label){const g=await page.evaluate(()=>({x:document.documentElement.scrollWidth-innerWidth,y:document.documentElement.scrollHeight-innerHeight,hours:document.querySelectorAll('.hour').length,setup:!document.getElementById('setupState').hidden,status:document.getElementById('statusLabel').textContent}));if(g.x>.5||g.y>.5)throw new Error(`${label}: overflow ${JSON.stringify(g)}`);return g;}
async function fixtureCase(browser,entry,label,{pro=false,fixture='clear',unit='°F',preview=false,stale=false,slot='M_H',after}={}){const [w,h]=SLOTS[slot],page=await browser.newPage({viewport:{width:w,height:h}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await baseInit(page,{pro,fixture,unit,preview,stale,locations:pro?['Phoenix','Seattle','Oslo']:['Phoenix']});await page.goto(pathToFileURL(entry).href,{waitUntil:'load'});await waitReady(page);if(after)await after(page);const g=await assertGeometry(page,label);if(g.setup)throw new Error(`${label}: unexpectedly in setup state`);if(errors.length)throw new Error(`${label}: ${errors.join(' | ')}`);await page.close();return g;}
async function networkCase(browser,entry,{pro=false,slow=false,failAfterSuccess=false,noCache=false,locationChange=false}={}){const page=await browser.newPage({viewport:{width:840,height:696}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});let calls=0;await page.addInitScript(({pro})=>{window.iCUE={defaultTemperatureUnit:()=> '°F',isPreview:false,iCUELanguage:'en'};window.uniqueId='network-instance-'+Math.random();window.temperatureUnits='auto';window.theme='sky';window.refreshMinutes=20;window.weatherApiKey='qa-key';window.location1='Phoenix';window.location2=pro?'Seattle':'';window.location3='';},{pro});await page.route('https://api.weatherapi.com/**',async route=>{calls++;if(noCache||(failAfterSuccess&&calls>1)){await route.abort('failed');return;}if(slow)await new Promise(r=>setTimeout(r,1200));const url=new URL(route.request().url()),q=url.searchParams.get('q')||'Phoenix';await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(weatherApiPayload(q.includes('Seattle')?'Seattle':'Phoenix','rain'))});});await page.goto(pathToFileURL(entry).href,{waitUntil:'load'});await page.waitForTimeout(slow?250:50);if(slow){const s=await page.locator('#statusLabel').textContent();if(!/LOADING|REFRESHING/.test(s||''))throw new Error('slow response did not preserve loading state');}await waitReady(page).catch(()=>{});await page.waitForFunction(()=>document.querySelector('#statusLabel')?.textContent!=='LOADING',{timeout:5000}).catch(()=>{});if(noCache){const g=await assertGeometry(page,'no-cache');if(!g.setup)throw new Error('no-cache failure did not show setup');await page.close();return;}await page.waitForFunction(()=>document.querySelectorAll('.hour').length>0,{timeout:6000});if(locationChange){await page.evaluate(()=>{window.location1='Seattle';window.dispatchEvent(new Event('icue-property-changed'));});await page.waitForFunction(()=>document.getElementById('locationName')?.textContent==='Seattle',{timeout:6000});}if(failAfterSuccess){await page.evaluate(()=>window.__weatherTimeline.reload());await page.waitForFunction(()=>document.getElementById('statusLabel')?.textContent.includes('STALE'),{timeout:6000});}await assertGeometry(page,'network');if(errors.length)throw new Error(errors.join(' | '));await page.close();}
export async function runWeatherQa(entry,outDir,{pro=false}={}){await fs.access(entry);await fs.mkdir(outDir,{recursive:true});const browser=await chromium.launch({headless:true}),report={pro,cases:[]};try{for(const slot of Object.keys(SLOTS)){await fixtureCase(browser,entry,`slot-${slot}`,{pro,slot});report.cases.push(`slot-${slot}`);}for(const [name,opts] of Object.entries({hot:{fixture:'hot'},cold:{fixture:'cold'},rain:{fixture:'rain'},snow:{fixture:'snow'},night:{fixture:'night'},celsius:{fixture:'clear',unit:'°C'},fahrenheit:{fixture:'clear',unit:'°F'},stale:{fixture:'rain',stale:true},preview:{fixture:'clear',preview:true},longCity:{fixture:'long'}})){await fixtureCase(browser,entry,name,{pro,...opts});report.cases.push(name);}await fixtureCase(browser,entry,'sunrise-sunset',{pro,fixture:'clear',slot:'XL_H',after:async page=>{const count=await page.locator('.solar-marker').count();if(count<2)throw new Error(`expected solar markers, got ${count}`);}});report.cases.push('sunrise-sunset');await fixtureCase(browser,entry,'touch-detail',{pro,fixture:'rain',after:async page=>{await page.locator('.hour').nth(2).click();if(!await page.locator('#detailPanel').evaluate(el=>el.classList.contains('open')))throw new Error('detail did not open');await page.locator('#detailClose').click();}});report.cases.push('touch-detail');if(pro){await fixtureCase(browser,entry,'pro-pager',{pro,fixture:'clear',slot:'S_H',after:async page=>{const b=page.locator('#timelinePager');if(await b.isHidden())throw new Error('pager hidden');await b.click();if(!(await b.textContent()).includes('FIRST'))throw new Error('pager did not advance');}});report.cases.push('pro-pager');}await networkCase(browser,entry,{pro,slow:true});report.cases.push('slow-api');await networkCase(browser,entry,{pro,failAfterSuccess:true});report.cases.push('api-failure-stale-cache');await networkCase(browser,entry,{pro,noCache:true});report.cases.push('api-failure-no-cache');await networkCase(browser,entry,{pro,locationChange:true});report.cases.push('location-change');}finally{await browser.close();}report.count=report.cases.length;report.status='PASS';await fs.writeFile(path.join(outDir,'weather-qa-report.json'),JSON.stringify(report,null,2));console.log(`WEATHER QA PASS: ${path.basename(entry)} (${report.count} cases)`);}
