import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const source = resolve(root, "src");
const pluginRoot = resolve(root, "com.packrat.discord-bridge.sdPlugin");
const output = resolve(pluginRoot, "bin");
const pluginImages = resolve(pluginRoot, "imgs", "plugin");

const pluginIcon256 = "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAADMUlEQVR42u3dMU4qURiGYTE0iAVW9tC6IrbgetwCK7KF3oqGUFuQWGiMDsxM5vzf85Q33Fx+Du+ZM+LV2WK5uoNU914CBAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABAACAAEgABAACAAEAAIAAYAAQAAgABAACAAEAAIAAYAAQAAgABAACAAEAAIAAYAAQAAgABAACAAEAAIAAYAAQAAwsLmXYBzr/bbT4w+bnRfNFQAEAAIAAYAAQAAgABAACAAEAAIAAYAAQAAgABAACAAEAAIAASAALwECAAGAAEAAQc6no/GTzS35tz95eHwyvgByt7qvR1Z6K4SPn34Euu5CX+Z4ED5+9BXgxlW8/PV298Lw8dOvAH3tYY3uheHjpwfQ77I19yYIHz89gCEWrKE3Qfj4AoDgAIbbq5rYBcPH72q2WK68+zt5+Xid7Pjvz29D/xPFvijkCIQjEAjA+Wc6x4wpP7FidwKuALgCgABAACAAd8AN3geP+ZQq3QfXCWDMD2gm+FnYmE+p0mdhjkA4AoEAQAAgAPfBrd0Bj/nEfDco1OH/A4y0Ba73206PP2x2lcZ3BShyCpr48oePL4BhF6mJ5Q8fXwAQH8AQe1VD+1/4+ALof8GaW/7w8QXQ57I1uvzh4/9T8R+Oe1m8q7842Prah4/vJvimhSyz/OHjR18Bfi7nn9thyYUPH18Avy7w+XSMWvLw8UOPQDY84wsABAACAAGAABCAlwABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAoCWVPsNMeAKAAIAAYAAQAAgABAACAAEAAJAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABABT8QnQIaU3zm7J7AAAAABJRU5ErkJggg==";
const pluginIcon512 = "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAAHZklEQVR42u3dPU7DaBSGUYzcOKYwFX3SsqJsgfWwhayINump0kSp6VIgUKQoBn/3PacdDaP5fK8fO+KnG8bpAYA8j44AQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAAAQBAAAAQAAAEAIBKekdAJev9dtavf9jsHDLeAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAQAAAEAAABAAAAQBAAAAQAAAEAAABoCnn09EhGABi9Y4gfM9/+0erp2fnZgAQABKf7y7/rhuBAXCSAkDoe70bgQEwAAJA3Ob/+MXdBQyAcxYAgjbfXcAAGICSfBeQ5W/jv4gBwBsAS9lDT4IGwAB4AyBx+T0JGgADIABYPLcAA2AABIDglXMLMAAuigCQu2xuAQbApREActfMLcAAuEACQO6CuQUYAJdJAMhdLbcAA+BiCQC5S+UWYABcMgEAQAAIe57yDGgAXDgBIHeR3AIMgMsnAAAsUTeMk1PwDDWf18831/FmHy/vrf8v+G1x3gAAEACSHv9rPMM6OmMsAAAIAAACgBfnq3wKFH5oPgUSAAAEAAABIOSV2adA4cflUyABAEAAABAAAAQAAAEAQAAAEAAABKCuqt8x7UcBwg/KjwIIANdV/QMa/jJM+EH5yzACAIAAACAAAAgAAAIAgAAAIAAACEBd9b5j2g8BhB+XHwIQAAAEAAABoPwrs89/wg/N5z8CAIAAACAAlH9x9vlP+NH5/GfJumGcnMJiFfgV6n+8/+v9dtavf9jsDIAAeAPA8lh+B2gABAAAAcAzlKc/x2gABIDoRbL8BsCFEwAABICY5ylPfwbAJRMAEpfK8hsAF0sASFwty28AXCYBIHHBLL8BcIEEgMQ1s/wGwKURABKXzfIbABdFAEhcOctvAFwOASBx8Sy/AXAh2tU7ggK3gH/5nZE23wA4f28AJD4JWn4D4Ni9ARD3JGjzDYDTFgDi7gI23wA4YQGgmQ8E7nIjsPYGwJEKAFk3AmtvABygAFDqRvDN+XS05wbA+cTyXUDuCxgABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAABMARAGTqhnFyCgDeAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABABAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABABAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQAQAEcAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIAIAAACAAAAgCAAAAgAAAIAAACAECDvgAYwj1S/8HdHQAAAABJRU5ErkJggg==";

const categoryIcon = `<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 28 28" fill="none"><circle cx="8" cy="14" r="4" stroke="#FFFFFF" stroke-width="2.4"/><circle cx="20" cy="14" r="4" stroke="#FFFFFF" stroke-width="2.4"/><path d="M12 14h4M14 9v10" stroke="#FFFFFF" stroke-width="2.4" stroke-linecap="round"/></svg>`;
const categoryIcon2x = `<svg xmlns="http://www.w3.org/2000/svg" width="56" height="56" viewBox="0 0 28 28" fill="none"><circle cx="8" cy="14" r="4" stroke="#FFFFFF" stroke-width="2.4"/><circle cx="20" cy="14" r="4" stroke="#FFFFFF" stroke-width="2.4"/><path d="M12 14h4M14 9v10" stroke="#FFFFFF" stroke-width="2.4" stroke-linecap="round"/></svg>`;
const actionIcon = `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none"><circle cx="6" cy="10" r="3" stroke="#FFFFFF" stroke-width="1.8"/><circle cx="14" cy="10" r="3" stroke="#FFFFFF" stroke-width="1.8"/><path d="M9 10h2M10 6.5v7" stroke="#FFFFFF" stroke-width="1.8" stroke-linecap="round"/></svg>`;
const keyIcon = `<svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 144 144" fill="none"><rect width="144" height="144" rx="28" fill="#090B10"/><circle cx="45" cy="72" r="20" stroke="#2BE86A" stroke-width="8"/><circle cx="99" cy="72" r="20" stroke="#2BE86A" stroke-width="8"/><path d="M65 72h14M72 48v48" stroke="#F4F6F8" stroke-width="8" stroke-linecap="round"/></svg>`;

await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
for (const name of ["protocol.js", "discord-ipc.js", "local-bridge.js", "streamkit-rpc.js", "plugin.js"]) {
  await cp(resolve(source, name), resolve(output, name));
}
await mkdir(pluginImages, { recursive: true });
await writeFile(resolve(pluginImages, "icon.png"), Buffer.from(pluginIcon256, "base64"));
await writeFile(resolve(pluginImages, "icon@2x.png"), Buffer.from(pluginIcon512, "base64"));
const categoryImages = resolve(pluginRoot, "imgs", "category");
const actionImages = resolve(pluginRoot, "imgs", "actions", "status");
await mkdir(categoryImages, { recursive: true });
await mkdir(actionImages, { recursive: true });
await writeFile(resolve(categoryImages, "icon.svg"), categoryIcon);
await writeFile(resolve(categoryImages, "icon@2x.svg"), categoryIcon2x);
await writeFile(resolve(actionImages, "icon.svg"), actionIcon);
await writeFile(resolve(actionImages, "key.svg"), keyIcon);
console.log(`Built Discord Bridge into ${output}`);
