"""Flatten a widget source tree into the single-file index.html iCUE requires.

Canonical RatPack XENEON build tool.

Sources live in widgets/_src/<slug>/ and shipping files live in widgets/<slug>/.
Local stylesheets and classic scripts referenced by the source HTML are inlined into
widgets/<slug>/index.html before official iCUE validation and packaging.

The generated document also installs a tiny compatibility bridge for iCUE property
controls. Current iCUE injects controls as JavaScript bindings before widget scripts;
some older RatPack widgets read settings through globalThis. The bridge exposes live
getters for those injected bindings without copying or caching the values, so changes
received through onDataUpdated are visible immediately in both access patterns.

Usage:
    python tools/xeneon/inline.py <slug>
    python tools/xeneon/inline.py <slug> --check
"""
import argparse
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
WIDGETS = REPO / "widgets"
BANNER = ("<!-- GENERATED by tools/xeneon/inline.py from widgets/_src/. "
          "Do not edit; your changes will be overwritten. -->\n")

VOID = ("area", "base", "br", "col", "embed", "hr", "img", "input",
        "link", "meta", "param", "source", "track", "wbr")
LINK_RE = re.compile(r"""<link\b[^>]*\brel\s*=\s*["']stylesheet["'][^>]*>""", re.I)
SCRIPT_RE = re.compile(r"""<script\b([^>]*)\bsrc\s*=\s*["']([^"']+)["']([^>]*)>\s*</script>""", re.I)
HREF_RE = re.compile(r"""\bhref\s*=\s*["']([^"']+)["']""", re.I)
BLOCK_RE = re.compile(r"<script\b.*?</script>|<style\b.*?</style>", re.S | re.I)
META_RE = re.compile(r"<meta\b[^>]*>", re.I)
NAME_RE = re.compile(r"""\bname\s*=\s*["']([^"']+)["']""", re.I)
CONTENT_RE = re.compile(r"""\bcontent\s*=\s*["']([^"']+)["']""", re.I)
JS_IDENTIFIER_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def die(msg):
    print(f"FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def read_asset(src_dir: Path, ref: str, kind: str) -> str:
    if ref.startswith(("http://", "https://", "//")):
        die(f"{kind} '{ref}' is remote; vendor it into the repository first")
    path = (src_dir / ref).resolve()
    if not path.exists():
        die(f"{kind} '{ref}' does not exist (looked in {path})")
    if WIDGETS not in path.parents:
        die(f"{kind} '{ref}' resolves outside widgets/ ({path})")
    return path.read_text(encoding="utf-8")


def self_close_void(html: str) -> str:
    def fix(match):
        tag = match.group(0)
        return tag if tag.rstrip().endswith("/>") else tag[:-1].rstrip() + " />"
    return re.sub(rf"<(?:{'|'.join(VOID)})\b[^>]*>", fix, html)


def icue_property_names(html: str) -> list[str]:
    names = []
    for match in META_RE.finditer(html):
        tag = match.group(0)
        name_match = NAME_RE.search(tag)
        if not name_match or name_match.group(1).lower() != "x-icue-property":
            continue
        content_match = CONTENT_RE.search(tag)
        if not content_match:
            continue
        name = content_match.group(1).strip()
        if JS_IDENTIFIER_RE.match(name) and name not in names:
            names.append(name)
    return names


def binding_bridge(html: str) -> str:
    names = icue_property_names(html)
    if not names:
        return ""
    encoded = json.dumps(names, ensure_ascii=True, separators=(",", ":"))
    return f"""<script>
(function () {{
  var names = {encoded};
  names.forEach(function (name) {{
    try {{
      if (Object.prototype.hasOwnProperty.call(globalThis, name)) return;
      var resolve = Function("return typeof " + name + " !== 'undefined' ? " + name + " : undefined;");
      if (resolve() === undefined) return;
      Object.defineProperty(globalThis, name, {{
        configurable: true,
        enumerable: true,
        get: function () {{ try {{ return resolve(); }} catch (error) {{ return undefined; }} }}
      }});
    }} catch (error) {{}}
  }});
  globalThis.__ratpackIcueBindingBridge = {{ version: 1, names: names.slice() }};
}})();
</script>"""


def build(slug: str, check_only: bool) -> None:
    wdir = WIDGETS / slug
    src_dir = WIDGETS / "_src" / slug
    if not src_dir.is_dir():
        die(f"no widgets/_src/{slug}/ directory")
    entry = src_dir / "index.html"
    if not entry.exists():
        die(f"no widgets/_src/{slug}/index.html")
    if not wdir.is_dir():
        die(f"no widgets/{slug}/ package directory")

    html = entry.read_text(encoding="utf-8")

    def inline_link(match):
        href = HREF_RE.search(match.group(0))
        if not href:
            return match.group(0)
        css = read_asset(src_dir, href.group(1), "stylesheet")
        return f"<style>\n{css.rstrip()}\n</style>"

    def inline_script(match):
        before, ref, after = match.group(1), match.group(2), match.group(3)
        if ref.startswith(("common/", "../common/")):
            return match.group(0)
        js = read_asset(src_dir, ref, "script")
        attrs = (before + after).replace(" ", "")
        if "type=" in attrs and "module" in attrs:
            die(f"script '{ref}' is type=module; use a classic script for iCUE inlining")
        return f"<script>\n{js.rstrip()}\n</script>"

    html = LINK_RE.sub(inline_link, html)
    html = SCRIPT_RE.sub(inline_script, html)

    bridge = binding_bridge(html)
    if bridge:
        if "</head>" not in html:
            die("no </head> in built document")
        html = html.replace("</head>", bridge + "\n</head>", 1)

    parts, last = [], 0
    for match in BLOCK_RE.finditer(html):
        parts.append(self_close_void(html[last:match.start()]))
        parts.append(match.group(0))
        last = match.end()
    parts.append(self_close_void(html[last:]))
    html = "".join(parts)

    head = re.search(r"<head>(.*?)</head>", html, re.S)
    if not head:
        die("no <head> in built document")
    try:
        ET.fromstring("<head>" + BLOCK_RE.sub("", head.group(1)) + "</head>")
    except ET.ParseError as exc:
        die(f"head is not well formed XML after inlining: {exc}")

    out = wdir / "index.html"
    built = BANNER + html
    if check_only:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != built:
            die(f"{slug}/index.html is stale; run: python tools/xeneon/inline.py {slug}")
        print(f"OK   {slug}: index.html is up to date")
        return

    out.write_text(built, encoding="utf-8")
    print(f"OK   {slug}: generated {out.relative_to(REPO)} ({len(built):,} chars)")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("slug")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    build(args.slug, args.check)


if __name__ == "__main__":
    main()
